sudo: required
dist: trusty

language: julia

os:
  - linux

julia:
  - nightly

script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Primme"); Pkg.test("Primme"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("Primme")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
